name: Compilar Plugin Cloudstream

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio actual
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Descargar Compilador Publico
        run: |
          git clone https://github.com/recloudstream/cloudstream compilador

      - name: Preparar archivo del plugin
        run: |
          mkdir -p compilador/app/src/main/java/com/lagradost
          cp CinemaCity.kt compilador/app/src/main/java/com/lagradost/CinemaCity.kt

      - name: Ejecutar compilacion
        run: |
          cd compilador
          chmod +x gradlew
          ./gradlew assembleDebug
